use_frameworks!

target 'Addendum_Example' do
  pod 'Addendum', :path => '../'

  target 'Addendum_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
