osx_image: xcode11.2
language: swift
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/Addendum.xcworkspace -scheme Addendum-Example -sdk iphonesimulator13.2 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint

